version: '3'

services:
  app:
    image: app:latest
    build: ../../
    hostname: app
    container_name: app
    ports:
      - 8080:8080
    volumes:
      - ./etc/config.yml:/etc/app/config.yml
    depends_on:
      - postgres
    networks:
      - app
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    hostname: postgres
    container_name: app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - app_postgres_data:/var/lib/postgresql/data
    networks:
      - app
    restart: unless-stopped

volumes:
  app_postgres_data:

networks:
  app:
